keywords = {
          "at":"and",
          "o":"or",
          "totoo": "True",
          "mali":"False",
          "wala":"None",
          "andar":"def",
          "klase":"class",
          "sarili":"self",
          "galing_sa":"from",
          "humango":"import",
          "bilang":"as",
          "pabalik":"return",
          "pasa":"pass",
          "itaas":"raise",
          "ituloy":"continue",
          "katumbas_ng":"==",
          "ay_gawing":"=",
          "mas_maliit_sa":"<",
          "mas_malaki_sa":">",
          "mas_maliit_sa_o_katumbas_ng":"<=",
          "mas_malaki_sa_o_katumbas_ng":">=",
          "hindi_katumbas_ng":"!=",
          "idagdag_sa":"+=",
          "kung":"if",
          "eh_paano_kung":"elif",
          "kundi":"else",
          "bawat":"for",
          "na_nasa":"in",
          # AYAW NYA GUMANA HUHUUUUUUUUUUUUU TANGA BA AKO
          "wala_sa":"not in",
          "habang":"while",
          "wakas":"break",
          "subukan":"try",
          "maliban":"except",
          "sa_wakas":"finally",
          "igiit":"assert",
          "isagawa":"exec",
          "sulat":"print",
          "kasama":"with",
          "ani":"yield",
          "kabuuan":"int",
          "matematika":"math",
          "magpalagay": "input"
}

splitters = [
    " ",
    ".",
    ",",
    "{",
    "}",
    "(",
    ")",
    "[",
    "]",
    "+",
    "-",
    "/",
    "*",
    "\t",
    "\"",
    "\'",
    "\t",
    "\n",
]
