keywords = {
          "at": "and",
          "o": "or",
          "totoo": "True",
          "mali": "False",
          "wala": "None",
          "andar": "def",
          "klase": "class",
          "sarili": "self",
          "galing_sa": "from",
          "humango": "import",
          "bilang": "as",
          "pabalik": "return",
          "pasa": "pass",
          "itaas": "raise",
          "ituloy": "continue",
          "kung": "if",
          "eh_paano_kung": "elif",
          "ay_gawing": "=",
          "kundi": "else",
          "bawat": "for",
          "nasa": "in",
          "hindi": "not",
          "habang": "while",
          "wakas": "break",
          "subukan": "try",
          "maliban": "except",
          "sa_wakas": "finally",
          "igiit": "assert",
          "isagawa": "exec",
          "sulat": "print",
          "kasama": "with",
          "ani": "yield",
          "kabuuan": "int",
          "matematika": "math",
          "magpalagay": "input",
          "kada": "for",
          "saklaw": "range"
}

splitters = [
    " ",
    ".",
    ",",
    "{",
    "}",
    "(",
    ")",
    "[",
    "]",
    "+",
    "-",
    "/",
    "*",
    "\t",
    "\"",
    "\'",
    "\t",
    "\n",
]
